[package]
name = "larrow"
version = "1.0.0"
entrypoint = "larrow.typ"
authors = ["@Mambouna"]
license = "MPL-2.0"
description = "Draw and style arrows between labels."
repository = "https://github.com/Mambouna/larrow"
keywords = ["arrow", "arrows", "label", "labels"]
categories = ["Components", "Visualization", "Utility"]
exclude = ["example"]
